name: CI/CD for Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Dependencies
        run: mvn install

      - name: Run Tests
        run: mvn test
        continue-on-error: true

      - name: Notify on Failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          to: recipient@example.com
          subject: "Test Failure in CI/CD Pipeline"
          body: |
            Hello,
            The tests in the GitHub Actions pipeline have failed.
            Please review the logs and take necessary action.
