name: Maven CI/CD with Notifications

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      # Step 3: Cache Maven Dependencies
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Run Maven Build with Explicit Exit Code Handling
      - name: Run Maven Build
        run: |
          mvn clean install
          if [ $? -ne 0 ]; then
            echo "Build failed! Exiting with code 1."
            exit 1
          fi

      # Step 5: Upload Surefire Reports (Optional for Test Reports)
      - name: Upload Surefire Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: surefire-reports
          path: target/surefire-reports/

  notify:
    needs: build
    if: failure()
    runs-on: ubuntu-latest

    steps:
      # Send Email Notification if Build Fails
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Build Failed: ${{ github.repository }}"
          body: |
            Hello,

            The build for the repository ${{ github.repository }} has failed.
            
            Branch: ${{ github.ref }}
            Commit: ${{ github.sha }}
            Check details: ${{ github.run_url }}

            Regards,
            GitHub Actions
          to: sasitharanvaratharasa887@gmail.com.com
          from: ${{ secrets.SMTP_USERNAME }}
