name: Maven CI/CD with Email Notifications

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Dependencies and Run Tests
        run: mvn clean install

      - name: Generate Surefire Report
        run: mvn surefire-report:report

      - name: Upload Surefire Reports
        uses: actions/upload-artifact@v3
        with:
          name: surefire-reports
          path: target/surefire-reports/

  notify:
    needs: build
    if: failure()
    runs-on: ubuntu-latest

    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Build Failed for ${{ github.repository }}"
          body: |
            Hello,

            The CI/CD build for the repository ${{ github.repository }} has failed.
            
            Branch: ${{ github.ref }}
            Commit: ${{ github.sha }}
            View details at: ${{ github.run_url }}
            
            Regards,
            GitHub Actions
          to: your-email@example.com
          from: no-reply@github.com
