name: CI/CD for Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Step 1: Run API Tests
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Dependencies
        run: mvn install

      - name: Run API Test Case 1
        run: mvn test -Dtest=DeleteBookAPITests

      - name: Run API Test Case 2
        run: mvn test -Dtest=GetBookAPITests

      - name: Run API Test Case 3
        run: mvn test -Dtest=PostBookAPITests

      - name: Run API Test Case 4
        run: mvn test -Dtest=PutBookAPITests

  # Step 2: Run UI Tests (Depends on API Tests)
  run-ui-tests:
    runs-on: ubuntu-latest
    needs: run-api-tests  # Ensures UI tests run only after API tests complete

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Dependencies
        run: mvn install

      - name: Run UI Test Case
        run: mvn test -Dtest=BuggyCarsUITests

  # Notify on Failure
  notify-on-failure:
    runs-on: ubuntu-latest
    needs:
      - run-api-tests
      - run-ui-tests  # This ensures notification runs only after both jobs
    if: failure()  # Trigger only if one of the jobs failed

    steps:
      - name: Notify on Failure
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          to: sasitharanvaratharasa887@gmail.com
          subject: "Test Failure in CI/CD Pipeline"
          body: |
            Hello,
            The tests in the GitHub Actions pipeline have failed.
            Please review the logs and take necessary action.
