name: CI/CD Pipeline with Email Notification

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install dependencies
        run: |
          ./mvnw clean install

      - name: Run tests
        run: |
          ./mvnw test
        continue-on-error: true

      - name: Check for test failures
        id: test-results
        run: |
          if grep -q "<failure>" target/surefire-reports/*; then
            echo "failure=true" >> $GITHUB_ENV
          else
            echo "failure=false" >> $GITHUB_ENV
          fi

      - name: Archive test reports
        if: env.failure == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: Test-Reports
          path: target/surefire-reports

      - name: Send email with reports
        if: env.failure == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Test Failure Notification
          body: |
            The CI/CD pipeline has detected test failures.
            Test reports are attached for review.
          to: "recipient@example.com"
          from: "noreply@example.com"
          attachments: target/surefire-reports/testng-results.xml
